name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarclousscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: SonarScan 
      uses: sonarsource/sonarcloud-github-action@master
      env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONARCUBE_TOKEN }}
      with:
        args: >
              -Dsonar.organization=spart
              # -Dsonar.projectKey=spart

  client:
    name: Client Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          client/package-lock.json
          client/package.json

    - name: Install client dependencies
      working-directory: ./client
      run: npm ci

    # - name: Run client linting
    #   working-directory: ./client
    #   run: npm run lint

    - name: Client type check
      working-directory: ./client
      run: npm run type-check || npx tsc --noEmit

    - name: Build client
      working-directory: ./client
      run: npm run build

  server:
    name: Server Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          server/package-lock.json
          server/package.json

    - name: Install server dependencies
      working-directory: ./server
      run: npm install && npm ci

    # - name: Run server linting
    #   working-directory: ./server
    #   run: npm run lint || echo "No lint script found"

    - name: Server type check
      working-directory: ./server
      run: npm run type-check || npx tsc --noEmit || echo "No type checking configured"

    - name: Build server
      working-directory: ./server
      run: npm run build || echo "No build script found" 
      